### PR TITLE
adding link and desc for wwyd4 and TO guide

### PR DESCRIPTION
**Pull request by tumultuous0**
files for wwyd4 and TO guide have been uploaded to /pr/ please copy to /mjg/

### CODE REVIEW

**Comment by chinponya** [comment]
Good work. Thanks!
Do you happen to have the translation for wwyd4 in some other format from which we can copy the text? I'd like to use it for the repo wwyd and it would be a lot easier this way. The previous wwyds had to be OCR'd for it and it required a ton of manual fixing that we could avoid.

**Comment by chinponya** [comment]
@tumultuous0
pls respond

**Comment by tumultuous0** [comment]
Nothing convenient, the individual pages are also saved as .svg Inkscape files which save the text in a text-box format. But opening each .svg and selecting each individual text box to obtain the text is probably equivalent work to OCR on the .pngs. I can catbox them if you think they would help.

Alternatively, if you make a separate and editable WWYD google to draft the wwyd4 entries I can paste the question numbers + responses there. We would have to make manual changes whenever tile images appear in the text

**Comment by chinponya** [comment]
It should be better, as it won't have any typos due to OCRing. Maybe I could even parse it and extract the text automatically.

**Comment by tumultuous0** [comment]
https://litter.catbox.moe/wyk9sc.zip
You may need the 'Wild Words' font, which dl'd here: https://www.freefontdownload.org/en/wild-words-roman.font

**Comment by tumultuous0** [comment]
@chinponya could you refresh the wwyd4 pdf in /mjg/ with the one just uploaded to /pr/ - fixed a typo and a corrupted image

**Comment by chinponya** [comment]
> @chinponya could you refresh the wwyd4 pdf in /mjg/ with the one just uploaded to /pr/ - fixed a typo and a corrupted image
done

**Pull request merged**
