### PR TITLE
wiki fix

### PR DESCRIPTION
**Pull request by nikaidou-agate**

### CODE REVIEW

**Comment by sharmayu** [comment]
Where's the wiki?

**Comment by Furitenman** [comment]
Where would you put the lolis if there's a wiki?

**Comment by sharmayu** [comment]
An entire wiki page dedicated to the best of the best loli doujins, favorite lewd loli pictures and much more if you click on the random page

**Comment by sharmayu** [comment]
ehhh not meme enough the other request was more meme

**Pull request closed without merging**
