### PR TITLE
deleto

### PR DESCRIPTION
**Pull request by nikaidou-agate**

### CODE REVIEW

**Comment by watterle** [comment]
based schizo

**Comment by sharmayu** [comment]
add a wiki version and this gets merged

**Comment by Furitenman** [comment]
It needs more deleting.

**Comment by watterle** [comment]
tfw deleting can't keep up with repo updates

**Comment by sharmayu** [comment]
whoa this pull is actually legit now

**Comment by sharmayu** [comment]
\>resolve conflicts
I don't know what to do with this

**Comment by Furitenman** [comment]
I'm doing it.

**Comment by watterle** [comment]
>conflicting files

**Pull request closed without merging**
